insert into game (title, genre, platform, esrb_rating) values ('Call of Duty: Modern Warfare 3', 'Multiplayer Shooter', 'Multiplatform', 'M');
insert into game (title, genre, platform, esrb_rating) values ('Terraria', '2D Sidescroller Sandbox', 'Multiplatform', 'E 10+');
insert into game (title, genre, platform, esrb_rating) values ('Grand Theft Auto: San Andreas', 'Open World Story Action Shooter', 'Multiplatform', 'M');
insert into game (title, genre, platform, esrb_rating) values ('Wii Play', 'Party', 'Nintendo Wii', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Duck Hunt', 'Hunting', 'Nintendo Entertainment System', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Pokémon Gold/Silver/Crystal', 'Turn-Based Battle RPG', 'Game Boy COLOR', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Diablo III & Reaper of Souls', 'Hack and Slash RPG', 'Multiplatformer', 'M');
insert into game (title, genre, platform, esrb_rating) values ('The Elder Scrolls V: Skyrim', 'Action RPG', 'Multiplatformer', 'M');
insert into game (title, genre, platform, esrb_rating) values ('New Super Mario Bros. Wii', 'Action Platformer', 'Wii', 'E');
insert into game (title, genre, platform, esrb_rating) values ('New Super Mario Bros', 'Action Platformer', 'Nintendo DS', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Wii Sports Resort', 'Sports Party', 'Wii', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Mario Kart Wii', 'Party Racing', 'Wii', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Wii Fit & Wii Fit Plus', 'Exercise Fitness Tracker', 'Wii', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Pokémon Red/Blue/Green/Yellow', 'Turn-Based Battle RPG', 'Game Boy', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Super Mario Bros', '2D Sidescroller', 'Super Nintendo', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Player Unknown’s Battlegrounds (PUBG)', 'Looter Shooter Royale', 'Multiplatformer', 'M');
insert into game (title, genre, platform, esrb_rating) values ('Wii Sports', 'Sports Party', 'Wii', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Grand Theft Auto V', 'Open World Story Action Shooter', 'Multiplatformer', 'M');
insert into game (title, genre, platform, esrb_rating) values ('Tetris', 'Puzzle', 'Multiplatformer', 'E');
insert into game (title, genre, platform, esrb_rating) values ('Minecraft', 'Open World Sandbox', 'Multiplatformer', 'E');